require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
  Max: 30

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
