---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/pokemons":
    get:
      summary: Lists all pokemons
      tags:
      - Pokemons
      responses:
        '200':
          description: Pokemons found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    types:
                      type: array
                      items:
                        type: string
  "/pokemons/{id}":
    get:
      summary: Retrieves a pokemon
      tags:
      - Pokemons
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Pokemons found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  base_experience:
                    type: integer
                  height:
                    type: integer
                  is_default:
                    type: boolean
                  name:
                    type: string
                  order:
                    type: integer
                  weight:
                    type: integer
                  poke_api_id:
                    type: integer
                  types:
                    type: array
                    items:
                      type: string
        '404':
          description: Pokemons not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
