json.id @pokemon.id
json.base_experience @pokemon.base_experience
json.height @pokemon.height
json.is_default @pokemon.is_default
json.name @pokemon.name
json.order @pokemon.order
json.weight @pokemon.weight
json.poke_api_id @pokemon.poke_api_id
json.types @pokemon.type_names
